"""add votes to comment reply

Revision ID: cf4add29bdfc
Revises: 35244a995931
Create Date: 2025-08-10 23:22:57.338387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4add29bdfc'
down_revision: Union[str, Sequence[str], None] = '35244a995931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_comment_replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_comment_replies', schema=None) as batch_op:
        batch_op.drop_column('votes')

    # ### end Alembic commands ###
